

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.awt.Color;
import java.awt.Label;
import java.sql.DriverManager;
import java.sql.ResultSet;
import static javafx.scene.paint.Color.color;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author PITA 28
 */
public class admin extends javax.swing.JFrame {
ResultSet rs;
Connection con;
Statement stmt;
    /**
     * Creates new form admin
     */
    public admin() {
        this.setContentPane(new JLabel(new ImageIcon("mybg.png")));
        initComponents();
       // this.setContentPane(new JLabel(new ImageIcon("mybg.jpg")));
     Color ca=new Color(11,83,146);
        jPanel1.setBackground(ca);
        jButton1.setBackground(ca);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tuser = new javax.swing.JTextField();
        tpass = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        tcom = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cinema Ticket Management");
        setBackground(new java.awt.Color(255, 255, 255));
        setBounds(new java.awt.Rectangle(0, 0, 415, 340));
        setForeground(new java.awt.Color(255, 255, 255));
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 416, 340));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("User Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 170, 70, 20);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Password");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 220, 70, 20);

        tuser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(tuser);
        tuser.setBounds(190, 170, 130, 26);

        tpass.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tpassActionPerformed(evt);
            }
        });
        getContentPane().add(tpass);
        tpass.setBounds(190, 220, 130, 26);

        jButton1.setBackground(new java.awt.Color(11, 83, 146));
        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(170, 270, 80, 35);

        tcom.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tcom.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Admin", "Operator" }));
        tcom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tcomActionPerformed(evt);
            }
        });
        getContentPane().add(tcom);
        tcom.setBounds(80, 120, 240, 30);

        jPanel1.setBackground(new java.awt.Color(11, 83, 146));
        jPanel1.setLayout(null);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ad.jpg"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(180, 10, 53, 49);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 410, 70);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setBackground(new java.awt.Color(51, 0, 51));
        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 198, 38));
        jLabel1.setText("LogIn");
        jPanel2.add(jLabel1);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 70, 410, 30);

        setSize(new java.awt.Dimension(414, 358));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
try{
    String s=tuser.getText();
    String s1=tpass.getText();
    Class.forName("com.mysql.jdbc.Driver");

con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/cinema", global.user,global.pass);
        
stmt=(Statement)con.createStatement();
if(tcom.getSelectedIndex()==0)
{
rs=stmt.executeQuery("select * from admin where username="+"'"+s+"'"+"and password="+"'"+s1+"'");//Use single quotes with string
if(rs.next())
{
   JOptionPane.showMessageDialog(this,"Sucessfully Login","Done", JOptionPane.INFORMATION_MESSAGE);
   new start().setVisible(true);
}
else
{
    JOptionPane.showMessageDialog(this,"Wrong Credentials","Error", JOptionPane.ERROR_MESSAGE);
}
}
else
{
rs=stmt.executeQuery("select * from operator where name="+"'"+s+"'"+"and password="+"'"+s1+"'");//Use single quotes with string
if(rs.next())
{
   JOptionPane.showMessageDialog(this,"Sucessfully Login","Done", JOptionPane.INFORMATION_MESSAGE);
   new start_oper().setVisible(true);
   global.id=s;
}
else
{
    JOptionPane.showMessageDialog(this,"Wrong Credentials","Error", JOptionPane.ERROR_MESSAGE);
}
}
tuser.setText("");
        tpass.setText("");}
catch(Exception e)
{
e.printStackTrace();
}
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tpassActionPerformed

    private void tcomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tcomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tcomActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Window".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JComboBox tcom;
    private javax.swing.JPasswordField tpass;
    private javax.swing.JTextField tuser;
    // End of variables declaration//GEN-END:variables
}
