
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author PITA 28
 */
public class chg_pass extends javax.swing.JFrame {
ResultSet rs;
Connection con;
Statement stmt;
    /** Creates new form chg_pass */
    public chg_pass() {
        this.setContentPane(new JLabel(new ImageIcon("mybg.png")));
        
        initComponents();
        try{
Class.forName("com.mysql.jdbc.Driver");

con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/cinema", global.user,global.pass);
        
stmt=(Statement)con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        tnew2 = new javax.swing.JPasswordField();
        tnew1 = new javax.swing.JPasswordField();
        told = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cinema Ticket Management");
        setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Existing Password");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 130, 110, 20);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("New Password");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 170, 89, 20);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Confirm Password");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 220, 120, 20);

        jButton1.setBackground(new java.awt.Color(11, 83, 146));
        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Change");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(130, 270, 110, 35);
        getContentPane().add(tnew2);
        tnew2.setBounds(210, 220, 130, 30);
        getContentPane().add(tnew1);
        tnew1.setBounds(210, 170, 130, 30);
        getContentPane().add(told);
        told.setBounds(210, 130, 130, 30);

        jPanel1.setBackground(new java.awt.Color(11, 83, 146));
        jPanel1.setLayout(null);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my cine viewR.png"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 10, 160, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 410, 75);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel5.setBackground(new java.awt.Color(51, 0, 51));
        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 198, 38));
        jLabel5.setText("                                   Change Password");
        jPanel2.add(jLabel5);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 75, 410, 30);

        setSize(new java.awt.Dimension(416, 358));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
try{
    String new1=tnew1.getText();
    String new2=tnew2.getText();
    
    if(new1.equals(new2)){
int stat=JOptionPane.showConfirmDialog(this,"Are you Sure to Change Password","", JOptionPane.YES_NO_OPTION);
if(stat==JOptionPane.YES_OPTION){
    rs=stmt.executeQuery("select * from admin");
    if(rs.next()){
       String oldp=told.getText();
       if(oldp.equals(rs.getString("password"))){
           rs.updateString("password",new1);
           rs.updateRow();
           JOptionPane.showMessageDialog(this,"Password Changed Successfully");
           tnew1.setText("");
       tnew2.setText("");
       told.setText("");
       }
       else{
           JOptionPane.showMessageDialog(this,"Old Password Not Match");
       }
    }
}
}
        else{
               JOptionPane.showMessageDialog(this,"New Password Not Match");
        }
}catch(Exception e){
    e.printStackTrace();
}

// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Window".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(chg_pass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(chg_pass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(chg_pass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(chg_pass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new chg_pass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField tnew1;
    private javax.swing.JPasswordField tnew2;
    private javax.swing.JPasswordField told;
    // End of variables declaration//GEN-END:variables

}
