
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author PITA 28
 */
public class edit extends javax.swing.JFrame {

    /**
     * Creates new form edit
     */
    public edit() {
        this.setContentPane(new JLabel(new ImageIcon("mybg.png")));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tname = new javax.swing.JTextField();
        tphone = new javax.swing.JTextField();
        tdel = new javax.swing.JButton();
        tupdate = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        tid = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Name");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 170, 50, 20);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Phone");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 210, 39, 20);

        tname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(tname);
        tname.setBounds(170, 170, 120, 30);

        tphone.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(tphone);
        tphone.setBounds(170, 220, 120, 30);

        tdel.setBackground(new java.awt.Color(11, 83, 146));
        tdel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tdel.setForeground(new java.awt.Color(255, 255, 255));
        tdel.setText("Delete");
        tdel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tdel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tdelActionPerformed(evt);
            }
        });
        getContentPane().add(tdel);
        tdel.setBounds(90, 270, 80, 35);

        tupdate.setBackground(new java.awt.Color(11, 83, 146));
        tupdate.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tupdate.setForeground(new java.awt.Color(255, 255, 255));
        tupdate.setText("Update");
        tupdate.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tupdateActionPerformed(evt);
            }
        });
        getContentPane().add(tupdate);
        tupdate.setBounds(200, 270, 90, 35);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("ID");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 120, 30, 20);

        tid.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tidActionPerformed(evt);
            }
        });
        getContentPane().add(tid);
        tid.setBounds(170, 120, 120, 30);

        jButton1.setBackground(new java.awt.Color(11, 83, 146));
        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Search");
        jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(310, 120, 80, 35);

        jPanel1.setBackground(new java.awt.Color(11, 83, 146));
        jPanel1.setLayout(null);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my cine viewR.png"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 10, 160, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 410, 75);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel6.setBackground(new java.awt.Color(51, 0, 51));
        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 198, 38));
        jLabel6.setText("                                Update or Delete Operator");
        jPanel2.add(jLabel6);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 75, 410, 30);

        setSize(new java.awt.Dimension(416, 359));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tidActionPerformed

    private void tdelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tdelActionPerformed
    try{   
        int id=Integer.parseInt(tid.getText());
        Class.forName("com.mysql.jdbc.Driver");

Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/cinema", global.user,global.pass);
Statement stmt=(Statement)con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
ResultSet rs=stmt.executeQuery("select * from operator where id ="+id);
// TODO add your handling code here:
if(rs.next())
{int status=JOptionPane.showConfirmDialog(this, "Are You Sure", "Delete "+rs.getString("name"),JOptionPane.ERROR_MESSAGE);
    if(status==JOptionPane.YES_OPTION){
        rs.deleteRow();
        tname.setText("");
        tid.setText("");
        tphone.setText("");
    }

}else{
     JOptionPane.showMessageDialog(this,"Deletion Not Successful","Error", JOptionPane.ERROR_MESSAGE);

}
    }
    catch(Exception e)
    {
        e.printStackTrace();
    }
    }//GEN-LAST:event_tdelActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      try{
          int id=Integer.parseInt(tid.getText());
        Class.forName("com.mysql.jdbc.Driver");

Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/cinema",global.user,global.pass);
Statement stmt=(Statement)con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
ResultSet rs=stmt.executeQuery("select * from operator where id ="+id);
// TODO add your handling code here:
if(rs.next())
{
     JOptionPane.showMessageDialog(this,"ID Found","Done", JOptionPane.INFORMATION_MESSAGE);

    tname.setText(rs.getString("name"));
    tphone.setText(rs.getString("phone"));
}else{
    JOptionPane.showMessageDialog(this,"Not Found","Error", JOptionPane.ERROR_MESSAGE);
}
    }
    catch(Exception e)
    {
        e.printStackTrace();
    } // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tupdateActionPerformed
        try{
          int id=Integer.parseInt(tid.getText());
        Class.forName("com.mysql.jdbc.Driver");

Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/cinema", global.user,global.pass);
Statement stmt=(Statement)con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
ResultSet rs=stmt.executeQuery("select * from operator where id ="+id);
// TODO add your handling code here:
if(rs.next())
{
    rs.updateString("name",tname.getText() );
    rs.updateString("phone", tphone.getText());
    rs.updateRow();
     JOptionPane.showMessageDialog(this,"Successfully Updated","Done", JOptionPane.INFORMATION_MESSAGE);
tname.setText("");
        tid.setText("");
        tphone.setText("");
}else{
     JOptionPane.showMessageDialog(this,"Updation Not Successful","Error", JOptionPane.ERROR_MESSAGE);

}
    }
    catch(Exception e)
    {
        e.printStackTrace();
    } /// TODO add your handling code here:
    }//GEN-LAST:event_tupdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Window".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new edit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton tdel;
    private javax.swing.JTextField tid;
    private javax.swing.JTextField tname;
    private javax.swing.JTextField tphone;
    private javax.swing.JButton tupdate;
    // End of variables declaration//GEN-END:variables
}
