
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author PITA 28
 */
public class jbook extends javax.swing.JFrame {
int ed=0;
int tat=0;
String s2;
int scr;
int d;
String star;
ArrayList<seat> al;
    /** Creates new form jbook */
    public jbook(int shon,int d,int scrn,ArrayList<seat> as,String fi,String star ) {
         this.setContentPane(new JLabel(new ImageIcon("jb.jpg")));
        initComponents();
 al=new ArrayList(as);
  this.scr=scrn;
  this.d=d;
  this.star=star;
        int i=fi.indexOf('(');
        int j=fi.indexOf(')');
        s2=fi.substring(0,i-1);
        String lang=fi.substring(i+1,j);
        if(fi.contains("3D")){
          ttype.setText("YES");  
        }
        else
        {
          ttype.setText("NO");
            
        }
tmov.setText(s2);
ttime.setText(star);
tlang.setText(lang);
tseat.setText(""+as.size());
int s=star.indexOf(":");
int ho=Integer.parseInt(star.substring(0,s));
int to;
if(ho<12){
tcost.setText(""+100);
to=100*as.size();
ttotal.setText(""+to);
    
}
else{
    tcost.setText(""+150);

to=150*as.size();
ttotal.setText(""+to); 
}
int dc=20*as.size();
dcost.setText(""+dc);
tat=dc+to;
tamt.setText(""+tat);


    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tmov = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        ttype = new javax.swing.JLabel();
        tlang = new javax.swing.JLabel();
        tseat = new javax.swing.JLabel();
        tcost = new javax.swing.JLabel();
        ttotal = new javax.swing.JLabel();
        ttime = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        dcost = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tamt = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tpa = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        tba = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cinema Ticket Management");
        setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Movie Name:-");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 120, 87, 20);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Start Time:-");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 150, 80, 20);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("3D:-");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 180, 27, 20);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Language:-");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 210, 70, 20);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Number of Seats:-");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 240, 111, 20);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Cost per Ticket:-");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 270, 100, 20);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Total Cost:-");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(40, 300, 71, 20);

        tmov.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tmov.setText("Movie name");
        getContentPane().add(tmov);
        tmov.setBounds(180, 120, 88, 21);
        getContentPane().add(jLabel9);
        jLabel9.setBounds(177, 87, 0, 0);

        ttype.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ttype.setText("3d");
        getContentPane().add(ttype);
        ttype.setBounds(180, 180, 75, 21);

        tlang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tlang.setText("Hindi");
        getContentPane().add(tlang);
        tlang.setBounds(180, 210, 60, 21);

        tseat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tseat.setText("Total");
        getContentPane().add(tseat);
        tseat.setBounds(180, 240, 26, 21);

        tcost.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tcost.setText("Rent ");
        getContentPane().add(tcost);
        tcost.setBounds(180, 270, 60, 21);

        ttotal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ttotal.setText("In rs");
        getContentPane().add(ttotal);
        ttotal.setBounds(180, 300, 60, 23);

        ttime.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ttime.setText("Time");
        getContentPane().add(ttime);
        ttime.setBounds(180, 150, 61, 23);

        jButton1.setBackground(new java.awt.Color(11, 83, 146));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Print Ticket");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(80, 470, 150, 35);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("3D charges");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(40, 330, 70, 20);

        dcost.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dcost.setText("in rs");
        getContentPane().add(dcost);
        dcost.setBounds(180, 330, 26, 20);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Total Amount");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(40, 360, 84, 20);

        tamt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tamt.setText("in rs");
        getContentPane().add(tamt);
        tamt.setBounds(180, 360, 60, 20);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Paid");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(40, 390, 50, 20);

        tpa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tpa.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                tpaCaretUpdate(evt);
            }
        });
        getContentPane().add(tpa);
        tpa.setBounds(180, 390, 70, 26);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Balance");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(40, 420, 50, 20);

        tba.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tba.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                tbaCaretUpdate(evt);
            }
        });
        getContentPane().add(tba);
        tba.setBounds(180, 420, 70, 26);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel12.setBackground(new java.awt.Color(51, 0, 51));
        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 198, 38));
        jLabel12.setText("                                                Order Detail");
        jPanel2.add(jLabel12);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 75, 360, 30);

        jPanel1.setBackground(new java.awt.Color(11, 83, 146));
        jPanel1.setLayout(null);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my cine viewR.png"))); // NOI18N
        jPanel1.add(jLabel15);
        jLabel15.setBounds(10, 10, 160, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 360, 75);

        setSize(new java.awt.Dimension(367, 556));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tpaCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_tpaCaretUpdate
       try{ed=Integer.parseInt(tpa.getText());
        System.out.println(ed);
       int bal=ed-tat;
if(bal>0){
tba.setText(""+bal);
    }
else{
tba.setText(""+bal);
    }
       }catch(Exception e){
           e.printStackTrace();
           JOptionPane.showMessageDialog(this, "Enter Paid Amount", "Error",JOptionPane.ERROR_MESSAGE);
       }
       // TODO add your handling code here:
    }//GEN-LAST:event_tpaCaretUpdate

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.out.println(al.size());
        new tic_print(al,s2,star,scr,d).setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tbaCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_tbaCaretUpdate
try{int ba=Integer.parseInt(tba.getText());
        if(ba>=0){
jButton1.setEnabled(true);
}else{
jButton1.setEnabled(false);
        }    }
catch(Exception e){
e.printStackTrace();
}// TODO add your handling code here:
    }//GEN-LAST:event_tbaCaretUpdate

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Window".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jbook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jbook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jbook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jbook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
         
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dcost;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel tamt;
    private javax.swing.JTextField tba;
    private javax.swing.JLabel tcost;
    private javax.swing.JLabel tlang;
    private javax.swing.JLabel tmov;
    private javax.swing.JTextField tpa;
    private javax.swing.JLabel tseat;
    private javax.swing.JLabel ttime;
    private javax.swing.JLabel ttotal;
    private javax.swing.JLabel ttype;
    // End of variables declaration//GEN-END:variables

}
