
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author PITA 28
 */
public class movie_add extends javax.swing.JFrame {

int i=0;
Connection con;
Statement stmt;
ResultSet rs;/** Creates new form movie_add */
    public movie_add() {
         this.setContentPane(new JLabel(new ImageIcon("mo_add.jpg")));
        initComponents();
        try{

        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tmov = new javax.swing.JTextField();
        tgrade = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tdes = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        ttime = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tadd = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        yes = new javax.swing.JRadioButton();
        no = new javax.swing.JRadioButton();
        langcombo = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cinema Ticket Management");
        setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Movie");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 120, 60, 20);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Grade");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 170, 50, 20);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Discription");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 220, 70, 20);

        tmov.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(tmov);
        tmov.setBounds(170, 120, 120, 30);

        tgrade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tgrade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "U", "Z" }));
        getContentPane().add(tgrade);
        tgrade.setBounds(170, 170, 41, 26);

        tdes.setColumns(20);
        tdes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tdes.setLineWrap(true);
        tdes.setRows(5);
        jScrollPane1.setViewportView(tdes);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(170, 220, 210, 106);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Time");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 350, 29, 20);

        ttime.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(ttime);
        ttime.setBounds(170, 350, 60, 26);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("minutes");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(240, 350, 49, 20);

        tadd.setBackground(new java.awt.Color(11, 83, 146));
        tadd.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tadd.setForeground(new java.awt.Color(255, 255, 255));
        tadd.setText("Add");
        tadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taddActionPerformed(evt);
            }
        });
        getContentPane().add(tadd);
        tadd.setBounds(140, 500, 100, 35);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Language");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(70, 400, 60, 20);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("3D");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(70, 450, 30, 20);

        yes.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(yes);
        yes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        yes.setText("Yes");
        getContentPane().add(yes);
        yes.setBounds(170, 450, 70, 29);

        no.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(no);
        no.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        no.setText("No");
        getContentPane().add(no);
        no.setBounds(250, 450, 80, 29);

        langcombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Hindi", "English", "Punjabi", "Tamil", "Urdu" }));
        getContentPane().add(langcombo);
        langcombo.setBounds(170, 400, 120, 30);

        jPanel1.setBackground(new java.awt.Color(11, 83, 146));
        jPanel1.setLayout(null);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my cine viewR.png"))); // NOI18N
        jPanel1.add(jLabel9);
        jLabel9.setBounds(10, 10, 160, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 410, 75);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel10.setBackground(new java.awt.Color(51, 0, 51));
        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 198, 38));
        jLabel10.setText("                                                            Add new Movie");
        jPanel2.add(jLabel10);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 75, 410, 30);

        setSize(new java.awt.Dimension(416, 579));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void taddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taddActionPerformed
try{
    if(yes.isSelected()){
        i=1;
    }
    if(no.isSelected()){
        i=0;
    }
    String s=tmov.getText();
String s1=tdes.getText();
String s2=tgrade.getSelectedItem().toString();
String s3=(String) langcombo.getSelectedItem();

int time=Integer.parseInt(ttime.getText());
    Class.forName("com.mysql.jdbc.Driver");

con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/cinema", global.user,global.pass);
stmt=(Statement)con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
rs=stmt.executeQuery("select * from movies");
        
rs.moveToInsertRow();
rs.updateString("movie",s);

rs.updateString("description",s1);

rs.updateString("grade",s2);

rs.updateInt("time", time);
rs.updateInt("3d",i);
rs.updateString("language",s3);
rs.insertRow();
JOptionPane.showMessageDialog(this,s+" Movie added Sucessfully","Success", JOptionPane.INFORMATION_MESSAGE);
tmov.setText("");
tdes.setText("");
ttime.setText("");
langcombo.setSelectedIndex(-1);
yes.setSelected(false);
no.setSelected(false);

}
catch(Exception e){
    e.printStackTrace();
JOptionPane.showMessageDialog(this," Movie not added Sucessfully","Failure", JOptionPane.ERROR_MESSAGE);

}
// TODO add your handling code here:
    }//GEN-LAST:event_taddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Window".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(movie_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(movie_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(movie_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(movie_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new movie_add().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox langcombo;
    private javax.swing.JRadioButton no;
    private javax.swing.JButton tadd;
    private javax.swing.JTextArea tdes;
    private javax.swing.JComboBox tgrade;
    private javax.swing.JTextField tmov;
    private javax.swing.JTextField ttime;
    private javax.swing.JRadioButton yes;
    // End of variables declaration//GEN-END:variables

}
