
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author PITA 28
 */
public class movie_edit extends javax.swing.JFrame {
Connection con;
Statement stmt;
ResultSet rs;
int i;
int j=0;
    /** Creates new form movie_edit */
    public movie_edit() {
         this.setContentPane(new JLabel(new ImageIcon("mo_edi.jpg")));
        initComponents();
try{
Class.forName("com.mysql.jdbc.Driver");
con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/cinema", global.user,global.pass);
stmt=(Statement)con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        tid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ttime = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tdes = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        tdelete = new javax.swing.JButton();
        tsearch = new javax.swing.JButton();
        tupdate = new javax.swing.JButton();
        tmov = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tgrade = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        yes = new javax.swing.JRadioButton();
        no = new javax.swing.JRadioButton();
        tlang = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cinema Ticket Management");
        setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("ID");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 120, 30, 20);

        tid.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(tid);
        tid.setBounds(170, 120, 120, 30);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Movie");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 170, 60, 20);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Discription");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 270, 100, 20);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Time");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 400, 29, 20);

        ttime.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(ttime);
        ttime.setBounds(170, 400, 50, 26);

        tdes.setColumns(10);
        tdes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tdes.setLineWrap(true);
        tdes.setRows(5);
        tdes.setOpaque(false);
        jScrollPane1.setViewportView(tdes);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(170, 270, 190, 106);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("mintutes");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(230, 410, 54, 20);

        tdelete.setBackground(new java.awt.Color(11, 83, 146));
        tdelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tdelete.setForeground(new java.awt.Color(255, 255, 255));
        tdelete.setText("Delete");
        tdelete.setPreferredSize(new java.awt.Dimension(73, 29));
        tdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tdeleteActionPerformed(evt);
            }
        });
        getContentPane().add(tdelete);
        tdelete.setBounds(70, 550, 80, 29);

        tsearch.setBackground(new java.awt.Color(11, 83, 146));
        tsearch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tsearch.setForeground(new java.awt.Color(255, 255, 255));
        tsearch.setText("Search");
        tsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tsearchActionPerformed(evt);
            }
        });
        getContentPane().add(tsearch);
        tsearch.setBounds(310, 120, 80, 29);

        tupdate.setBackground(new java.awt.Color(11, 83, 146));
        tupdate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tupdate.setForeground(new java.awt.Color(255, 255, 255));
        tupdate.setText("Update");
        tupdate.setPreferredSize(new java.awt.Dimension(73, 29));
        tupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tupdateActionPerformed(evt);
            }
        });
        getContentPane().add(tupdate);
        tupdate.setBounds(180, 550, 90, 29);

        tmov.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(tmov);
        tmov.setBounds(170, 170, 120, 30);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Grade");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(70, 220, 37, 20);

        tgrade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tgrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgradeActionPerformed(evt);
            }
        });
        getContentPane().add(tgrade);
        tgrade.setBounds(170, 220, 120, 30);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Language");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(70, 450, 60, 20);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("3D");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(70, 500, 30, 20);

        yes.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(yes);
        yes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        yes.setText("Yes");
        yes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesActionPerformed(evt);
            }
        });
        getContentPane().add(yes);
        yes.setBounds(180, 500, 70, 29);

        no.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(no);
        no.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        no.setText("No");
        no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noActionPerformed(evt);
            }
        });
        getContentPane().add(no);
        no.setBounds(250, 500, 80, 30);

        tlang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(tlang);
        tlang.setBounds(170, 450, 120, 30);

        jPanel1.setBackground(new java.awt.Color(11, 83, 146));
        jPanel1.setLayout(null);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my cine viewR.png"))); // NOI18N
        jPanel1.add(jLabel10);
        jLabel10.setBounds(10, 10, 160, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 410, 75);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel11.setBackground(new java.awt.Color(51, 0, 51));
        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 198, 38));
        jLabel11.setText("                                           Update or Delete Movie");
        jPanel2.add(jLabel11);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 75, 410, 30);

        setSize(new java.awt.Dimension(416, 620));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tsearchActionPerformed
try{
        i=Integer.parseInt(tid.getText());
rs=stmt.executeQuery("select * from movies where id="+i);
if(rs.next()){
    JOptionPane.showMessageDialog(this,"ID Found","Done", JOptionPane.INFORMATION_MESSAGE);

    tmov.setText(rs.getString("movie"));
    tdes.setText(rs.getString("description"));
     ttime.setText(rs.getString("time"));
      tgrade.setText(rs.getString("grade"));
      tlang.setText(rs.getString("language"));
      j=rs.getInt("3d");
      if(j==1){
          yes.setSelected(true);
      }
      else{
      no.setSelected(true);
          
      }
          
}else{
    JOptionPane.showMessageDialog(this,"Not Found","Error", JOptionPane.ERROR_MESSAGE);
}
}
catch(Exception e){
e.printStackTrace();}
    // TODO add your handling code here:
    }//GEN-LAST:event_tsearchActionPerformed

    private void tdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tdeleteActionPerformed
  try{
  
  int status=JOptionPane.showConfirmDialog(this,"Are you sure to delete","Error", JOptionPane.YES_NO_OPTION);   
  if(status==JOptionPane.YES_OPTION)
          {
              rs.deleteRow();
              JOptionPane.showMessageDialog(this, "Deletion sucessfully");
              tmov.setText("");
    tdes.setText("");
     ttime.setText("");
      tgrade.setText("");
      tlang.setText("")
            ;
      yes.setSelected(false);
      
      no.setSelected(false);
          }
 
  }catch(Exception e){
      e.printStackTrace();
  }// TODO add your handling code here:
    }//GEN-LAST:event_tdeleteActionPerformed

    private void tupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tupdateActionPerformed
    try{
        if(yes.isSelected()){
            j=1;
        }
        if(no.isSelected()){
        j=0;
    }
        rs=stmt.executeQuery("select * from movies where id="+i);
        if(rs.next())
{
    rs.updateString("movie",tmov.getText() );
    rs.updateString("grade", tgrade.getText());
    rs.updateInt("time", Integer.parseInt(ttime.getText()));
    rs.updateString("description", tdes.getText());
       rs.updateString("language", tlang.getText());
           rs.updateInt("3d", j);
    
    rs.updateRow();
     JOptionPane.showMessageDialog(this,"Successfully Updated","Done", JOptionPane.INFORMATION_MESSAGE);
tmov.setText("");
        tdes.setText("");
        tgrade.setText("");
         ttime.setText("");
         tlang.setText("");
         yes.setSelected(false);
         tid.setText("");
         no.setSelected(false);
}else{
     JOptionPane.showMessageDialog(this,"Updation Not Successful","Error", JOptionPane.ERROR_MESSAGE);

} }
    catch(Exception e){
        e.printStackTrace();
    }// }TODO add your handling code here:
    }//GEN-LAST:event_tupdateActionPerformed

    private void tgradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgradeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tgradeActionPerformed

    private void noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noActionPerformed

    private void yesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Window".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(movie_edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(movie_edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(movie_edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(movie_edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new movie_edit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton no;
    private javax.swing.JButton tdelete;
    private javax.swing.JTextArea tdes;
    private javax.swing.JTextField tgrade;
    private javax.swing.JTextField tid;
    private javax.swing.JTextField tlang;
    private javax.swing.JTextField tmov;
    private javax.swing.JButton tsearch;
    private javax.swing.JTextField ttime;
    private javax.swing.JButton tupdate;
    private javax.swing.JRadioButton yes;
    // End of variables declaration//GEN-END:variables

}
