
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.awt.Color;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.util.ArrayList;

import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.table.AbstractTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author PITA 28
 */
public class movie_view extends javax.swing.JFrame {
        
ArrayList<movielist> lst;
custommodel model1=new custommodel(); 

    /** Creates new form movie_view */
    public movie_view() {
        
            
        initComponents();
        this.getContentPane().setBackground(Color.WHITE);

try{
lst=new ArrayList();
Class.forName("com.mysql.jdbc.Driver");
Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/cinema", global.user,global.pass);
Statement stmt=(Statement)con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
ResultSet rs=stmt.executeQuery("select * from movies");
while(rs.next()){
    String mov=rs.getString("movie");
    String des=rs.getString("description");
    
    String grade=rs.getString("grade");
    int id=rs.getInt("id");
    int time=rs.getInt("time");
    int d3=rs.getInt("3d");
    String la=rs.getString("language");
lst.add(new movielist(mov,grade,des,la,d3,time,id));
//list1.add(new movielist(mov,des,grade,id));
    
}
jT.setModel(model1);



jT.getColumnModel().getColumn(0).setPreferredWidth(20);
jT.getColumnModel().getColumn(1).setPreferredWidth(150);
jT.getColumnModel().getColumn(2).setPreferredWidth(350);
jT.getColumnModel().getColumn(3).setPreferredWidth(70);
jT.getColumnModel().getColumn(4).setPreferredWidth(20);
jT.getColumnModel().getColumn(5).setPreferredWidth(40);
jT.getColumnModel().getColumn(6).setPreferredWidth(40);
jScrollPane1.getViewport().setOpaque(false);

jScrollPane1.setViewportBorder(null);
        }
    catch(Exception e){
        e.printStackTrace();
    }
    }                               

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jT = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cinema Ticket Management");
        setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().setLayout(null);

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);

        jT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ));
        jScrollPane1.setViewportView(jT);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 120, 690, 200);

        jPanel1.setBackground(new java.awt.Color(11, 83, 146));
        jPanel1.setLayout(null);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my cine viewR.png"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 10, 160, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 720, 75);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel5.setBackground(new java.awt.Color(51, 0, 51));
        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 198, 38));
        jLabel5.setText("                                                                                                                     Current running movies");
        jPanel2.add(jLabel5);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 75, 720, 30);

        setSize(new java.awt.Dimension(725, 364));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Window".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(movie_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(movie_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(movie_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(movie_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new movie_view().setVisible(true);
            }
        });
    }
class custommodel extends AbstractTableModel{
String name[]={"ID","Movie","Description","Language","3d","Grade","Time"};
public String getColumnName(int i) {
        return name[i];
    }       
@Override
        public int getRowCount() {
        return lst.size();
        }

        @Override
        public int getColumnCount() {
        return 7;
        }

        @Override
        public Object getValueAt(int rowIndex, int columnIndex) {
        movielist s=lst.get(rowIndex);
                if(columnIndex==0){
                    return s.id;
                }
 if(columnIndex==1){
                    return s.movie;
                }
  if(columnIndex==2){
                    return s.description;
                }
    if(columnIndex==3){
                    return s.language;
                }
  if(columnIndex==4){
                    return s.d3;
                }
if(columnIndex==5){
                    return s.grade;
                }
if(columnIndex==6){
                    return s.time;
                }
    
  return null;
        }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jT;
    // End of variables declaration//GEN-END:variables

}
