
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author PITA 28
 */
public class operator extends javax.swing.JFrame {

    /**
     * Creates new form operator
     */
    public operator() {
        this.setContentPane(new JLabel(new ImageIcon("mybg.png")));
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tname = new javax.swing.JTextField();
        tphone = new javax.swing.JTextField();
        tadd = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(90, 130, 60, 20);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Phone");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(90, 170, 60, 20);

        tname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(tname);
        tname.setBounds(190, 130, 140, 26);

        tphone.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tphoneActionPerformed(evt);
            }
        });
        tphone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tphoneKeyTyped(evt);
            }
        });
        getContentPane().add(tphone);
        tphone.setBounds(190, 170, 140, 26);

        tadd.setBackground(new java.awt.Color(11, 83, 146));
        tadd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tadd.setForeground(new java.awt.Color(255, 255, 255));
        tadd.setText("ADD");
        tadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taddActionPerformed(evt);
            }
        });
        getContentPane().add(tadd);
        tadd.setBounds(150, 270, 120, 30);

        jPanel1.setBackground(new java.awt.Color(11, 83, 146));
        jPanel1.setLayout(null);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my cine viewR.png"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 10, 160, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 410, 75);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel6.setBackground(new java.awt.Color(51, 0, 51));
        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 198, 38));
        jLabel6.setText("                                           Add Operator");
        jPanel2.add(jLabel6);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 75, 410, 30);

        setSize(new java.awt.Dimension(411, 355));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void taddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taddActionPerformed
     try{
         String s=tname.getText();
         String s1=tphone.getText();
         Class.forName("com.mysql.jdbc.Driver");

Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/cinema", global.user,global.pass);
Statement stmt=(Statement)con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
ResultSet rs=stmt.executeQuery("select * from operator");
rs.moveToInsertRow();
rs.updateString("name", s);
rs.updateString("phone", s1);
rs.insertRow();
JOptionPane.showMessageDialog(this,s+" Operator added Sucessfully","Success", JOptionPane.INFORMATION_MESSAGE);
tname.setText("");
tphone.setText("");
     }
     catch(Exception e){
         e.printStackTrace();
     }
    }//GEN-LAST:event_taddActionPerformed

    private void tphoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tphoneKeyTyped
char ch=evt.getKeyChar();
if(ch<='9'&&ch>='0'){
    
}
else
{
evt.consume();}

/*f(evt.getKeyChar()<=9){///////Key codeeeee
    tphone.setText("hello");
}
else{
evt.consume();}*/// TODO add your handling code here:
    }//GEN-LAST:event_tphoneKeyTyped

    private void tphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tphoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tphoneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Window".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(operator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(operator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(operator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(operator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new operator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton tadd;
    private javax.swing.JTextField tname;
    private javax.swing.JTextField tphone;
    // End of variables declaration//GEN-END:variables
}
