
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author PITA 28
 */
public class screen_time extends javax.swing.JFrame {
    
        
Connection con;
Statement stmt;
ResultSet rs;
    /** Creates new form screen_time */
    public screen_time() {
        this.setContentPane(new JLabel(new ImageIcon("mybg.png")));
        initComponents();

try{
Class.forName("com.mysql.jdbc.Driver");
con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/cinema", global.user,global.pass);
stmt=(Statement)con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tcomb = new javax.swing.JComboBox();
        supdate = new javax.swing.JButton();
        smin = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tseats = new javax.swing.JTextField();
        shrs = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cinema Ticket Management");
        setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Screen no");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 120, 90, 20);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Time");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(100, 170, 70, 20);

        tcomb.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tcomb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "1", "2", "3", "4" }));
        tcomb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tcombActionPerformed(evt);
            }
        });
        getContentPane().add(tcomb);
        tcomb.setBounds(200, 120, 66, 26);

        supdate.setBackground(new java.awt.Color(11, 83, 146));
        supdate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        supdate.setForeground(new java.awt.Color(255, 255, 255));
        supdate.setText("UPDATE");
        supdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supdateActionPerformed(evt);
            }
        });
        getContentPane().add(supdate);
        supdate.setBounds(160, 270, 90, 29);

        smin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(smin);
        smin.setBounds(230, 170, 20, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Seats");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(100, 220, 32, 20);

        tseats.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(tseats);
        tseats.setBounds(200, 220, 120, 26);

        shrs.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(shrs);
        shrs.setBounds(200, 170, 20, 30);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText(":");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(230, 170, 10, 20);

        jPanel1.setBackground(new java.awt.Color(11, 83, 146));
        jPanel1.setLayout(null);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my cine viewR.png"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 10, 160, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 410, 75);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel6.setBackground(new java.awt.Color(51, 0, 51));
        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 198, 38));
        jLabel6.setText("                       Update Timing and Seats of Screen");
        jPanel2.add(jLabel6);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 75, 410, 30);

        setSize(new java.awt.Dimension(412, 353));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tcombActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tcombActionPerformed
try{
        int i=tcomb.getSelectedIndex();

        rs=stmt.executeQuery("select * from screen where no="+i);
        if(rs.next()){
            JOptionPane.showMessageDialog(this,"Screen Found","Done", JOptionPane.INFORMATION_MESSAGE);
    smin.setText(rs.getString("start_min"));
     shrs.setText(rs.getString("start_hrs"));
        tseats.setText(rs.getString("seats"));
        
        }
        else{
            JOptionPane.showMessageDialog(this,"Select Appropiate Choice","", JOptionPane.ERROR_MESSAGE);
        }
   
}
catch(Exception e){
    e.printStackTrace();
}
// TODO add your handling code here:
    }//GEN-LAST:event_tcombActionPerformed

    private void supdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supdateActionPerformed
     try{
       //if(rs.next()){
       int s=JOptionPane.showConfirmDialog(this,"Are You Sure","", JOptionPane.YES_NO_OPTION);
       if(s==JOptionPane.YES_OPTION){
       
             rs.updateString("start_hrs", shrs.getText());
             rs.updateString("start_min", smin.getText());
       rs.updateString("seats", tseats.getText());
        rs.updateRow();
     smin.setText("");
     shrs.setText("");
     tseats.setText("");
       }
         //}else{
             JOptionPane.showMessageDialog(this,"Updation Successful","Done", JOptionPane.INFORMATION_MESSAGE);
       
         //}
     }
     catch(Exception e){
         JOptionPane.showMessageDialog(this,"Enter Appropiate Screen","Done", JOptionPane.ERROR_MESSAGE);
         e.printStackTrace();
     }
// TODO add your handling code here:
    }//GEN-LAST:event_supdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Window".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(screen_time.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(screen_time.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(screen_time.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(screen_time.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new screen_time().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField shrs;
    private javax.swing.JTextField smin;
    private javax.swing.JButton supdate;
    private javax.swing.JComboBox tcomb;
    private javax.swing.JTextField tseats;
    // End of variables declaration//GEN-END:variables

}
