
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.awt.Button;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author PITA 28
 */
public class seats extends javax.swing.JFrame {
ResultSet rs;
int i=1;
int x=30;
int y=150;
int show_id;
int seat;
int day_id=0;
int scr_id;
String movi;
String str;
ArrayList<Integer> al;
HashMap<Integer,JButton> list4;
ArrayList<seat> list3;
seat s3;
seat ms4;
ArrayList<JButton> al45;
Connection con;
Statement stmt;
int id;
Color ca;
    /** Creates new form seats */
    public seats(int sc,String start,int showid,String mov) {
        this.setContentPane(new JLabel(new ImageIcon("se.jpg")));
        initComponents();
        ca=new Color(11,83,146);
        try{
            movi=mov;
            str=start;
            al45=new ArrayList();
            al=new ArrayList();
            show_id=showid;
            id=showid;
            
            scr_id=sc;
            list3=new ArrayList();
            list4=new HashMap();
            tshowid.setText("Show ID: "+showid);
                    tstart.setText("Starting Time is: "+start);
         tscr.setText("Screen No: "+sc);
            lmov.setText(mov);
Class.forName("com.mysql.jdbc.Driver");
con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/cinema", global.user,global.pass);
stmt=(Statement)con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
 rs=stmt.executeQuery("select * from screen where no="+sc);
if(rs.next()){
    seat=rs.getInt("seats");
    

}
    
        }
    catch(Exception e){
    e.printStackTrace();
    }
     
     
        
    }
     class mylistener implements ActionListener{
JButton b;
int se;
mylistener(JButton b,int s){
    this.b=b;
    se=s;
}
        @Override
        public void actionPerformed(ActionEvent e) {
            if(day_id==0){
            JOptionPane.showMessageDialog(null,"Please Select Day","Error",JOptionPane.ERROR_MESSAGE);
            }
            else
            {
    if(b.getBackground()==Color.GREEN){
            b.setBackground(Color.red);
            b.setForeground(Color.white);
            s3=new seat(b,se);
            list3.add(s3);
            list4.put(se, b);
           ms4=new seat(b,day_id,se);
//            //list4.put(se,ms4 );
//list5.put(se, b);

    }
    else{
        b.setBackground(Color.green);
        b.setForeground(Color.black);
      list3.remove(s3);
      list4.remove(se);
//      //list4.remove(se);
//list5.remove(se,b);
    }
    }
            
            
        }
          
      }  

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lmov = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lscr = new javax.swing.JLabel();
        tscr = new javax.swing.JLabel();
        tstart = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        tshowid = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cinema Ticket Management");
        setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().setLayout(null);

        lmov.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lmov.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lmov);
        lmov.setBounds(210, 45, 360, 20);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(230, 10, 0, 0);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(260, 20, 0, 0);
        getContentPane().add(lscr);
        lscr.setBounds(170, 30, 0, 0);

        tscr.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(tscr);
        tscr.setBounds(30, 10, 180, 20);

        tstart.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(tstart);
        tstart.setBounds(310, 10, 180, 20);

        jButton1.setBackground(new java.awt.Color(11, 83, 146));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Friday");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(90, 90, 80, 30);

        jButton2.setBackground(new java.awt.Color(11, 83, 146));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Saturday");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(170, 90, 100, 30);

        jButton3.setBackground(new java.awt.Color(11, 83, 146));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Sunday");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(270, 90, 100, 30);

        jButton4.setBackground(new java.awt.Color(11, 83, 146));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Monday");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(370, 90, 100, 30);

        jButton5.setBackground(new java.awt.Color(11, 83, 146));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Tuesday");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(470, 90, 100, 30);

        jButton6.setBackground(new java.awt.Color(11, 83, 146));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Wednesday");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(570, 90, 120, 30);

        jButton7.setBackground(new java.awt.Color(11, 83, 146));
        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Thrusday");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(690, 90, 100, 30);

        jButton8.setBackground(new java.awt.Color(11, 83, 146));
        jButton8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("BOOK NOW");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(750, 45, 120, 35);

        tshowid.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(tshowid);
        tshowid.setBounds(650, 10, 80, 20);

        setSize(new java.awt.Dimension(913, 697));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
day_id=1;  
jButton1.setBackground(ca);
jButton2.setBackground(Color.white);

jButton3.setBackground(Color.white);

jButton4.setBackground(Color.white);

jButton5.setBackground(Color.white);

jButton6.setBackground(Color.white);

jButton7.setBackground(Color.white);// TODO add your handling code here:
jButton1.setForeground(Color.white);
jButton2.setForeground(Color.black);
jButton3.setForeground(Color.black);
jButton4.setForeground(Color.black);
jButton5.setForeground(Color.black);
jButton6.setForeground(Color.black);
jButton7.setForeground(Color.black);

enable(day_id);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
day_id=2;         // TODO add your handling code here:
jButton1.setBackground(Color.white);
jButton2.setBackground(ca);

jButton3.setBackground(Color.white);

jButton4.setBackground(Color.white);

jButton5.setBackground(Color.white);

jButton6.setBackground(Color.white);

jButton7.setBackground(Color.white);
jButton2.setForeground(Color.white);
jButton1.setForeground(Color.black);
jButton3.setForeground(Color.black);
jButton4.setForeground(Color.black);
jButton5.setForeground(Color.black);
jButton6.setForeground(Color.black);
jButton7.setForeground(Color.black);
enable(day_id);

       

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
day_id=3;         // TODO add your handling code here:
jButton1.setBackground(Color.white);
jButton2.setBackground(Color.white);

jButton3.setBackground(ca);

jButton4.setBackground(Color.white);

jButton5.setBackground(Color.white);

jButton6.setBackground(Color.white);

jButton7.setBackground(Color.white);
jButton3.setForeground(Color.white);
jButton1.setForeground(Color.black);
jButton2.setForeground(Color.black);
jButton4.setForeground(Color.black);
jButton5.setForeground(Color.black);
jButton6.setForeground(Color.black);
jButton7.setForeground(Color.black);
enable(day_id);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
day_id=4; 
jButton1.setBackground(Color.white);
jButton2.setBackground(Color.white);

jButton3.setBackground(Color.white);

jButton4.setBackground(ca);

jButton5.setBackground(Color.white);

jButton6.setBackground(Color.white);

jButton7.setBackground(Color.white);
jButton4.setForeground(Color.white);
jButton1.setForeground(Color.black);
jButton2.setForeground(Color.black);
jButton3.setForeground(Color.black);
jButton5.setForeground(Color.black);
jButton6.setForeground(Color.black);
jButton7.setForeground(Color.black);
enable(day_id);// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
day_id=5;
jButton1.setBackground(Color.white);
jButton5.setBackground(ca);

jButton3.setBackground(Color.white);

jButton4.setBackground(Color.white);

jButton2.setBackground(Color.white);

jButton6.setBackground(Color.white);

jButton7.setBackground(Color.white);
jButton5.setForeground(Color.white);
jButton1.setForeground(Color.black);
jButton2.setForeground(Color.black);
jButton3.setForeground(Color.black);
jButton4.setForeground(Color.black);
jButton6.setForeground(Color.black);
jButton7.setForeground(Color.black);
enable(day_id);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
day_id=6;
jButton1.setBackground(Color.white);
jButton6.setBackground(ca);

jButton3.setBackground(Color.white);

jButton4.setBackground(Color.white);

jButton5.setBackground(Color.white);

jButton2.setBackground(Color.white);

jButton7.setBackground(Color.white);
jButton6.setForeground(Color.white);
jButton1.setForeground(Color.black);
jButton2.setForeground(Color.black);
jButton3.setForeground(Color.black);
jButton4.setForeground(Color.black);
jButton5.setForeground(Color.black);
jButton7.setForeground(Color.black);
enable(day_id);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
day_id=7;
jButton1.setBackground(Color.white);
jButton7.setBackground(ca);

jButton3.setBackground(Color.white);

jButton4.setBackground(Color.white);

jButton5.setBackground(Color.white);

jButton6.setBackground(Color.white);

jButton2.setBackground(Color.white);
jButton7.setForeground(Color.white);
jButton1.setForeground(Color.black);
jButton2.setForeground(Color.black);
jButton3.setForeground(Color.black);
jButton4.setForeground(Color.black);
jButton5.setForeground(Color.black);
jButton6.setForeground(Color.black);
enable(day_id);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
try{
    if(day_id==0||list3.size()==0)
    {
        JOptionPane.showMessageDialog(this, "Plese Select Day and Seats","Error", JOptionPane.ERROR_MESSAGE);
    }
    else
    {
        rs=stmt.executeQuery("select * from booking");
            int stat=JOptionPane.showConfirmDialog(this, "Are You Sure","",JOptionPane.YES_NO_OPTION);
            if(stat==JOptionPane.YES_OPTION)
            {
            for(int i=0;i<list3.size();i++)
            {
            rs.moveToInsertRow();
            rs.updateInt("show_id",id);
            rs.updateInt("day_id",day_id);
            rs.updateString("movie", movi);
            rs.updateInt("screen_id",scr_id);
            rs.updateInt("seat_no",list3.get(i).seat);
            list3.get(i).bu.setBackground(Color.GRAY);
            list3.get(i).bu.setEnabled(false);
           
            rs.insertRow();
           // list2.get(i).setEnabled(false);
            }
            new jbook(show_id,day_id,scr_id,list3,movi,str).setVisible(true);
            list3.clear();
    }
            else
            {
                
            }
    }
    
        
}
catch(Exception e){
    e.printStackTrace();
}
// TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Window".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(seats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(seats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(seats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(seats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new seats().setVisible(true);
            }
        });
    }

    public void enable(int d){
       
        try{
            
rs=stmt.executeQuery("select * from booking where show_id="+show_id+" and screen_id="+scr_id+" and day_id="+d+" and movie="+"'"+movi+"'");
  ArrayList<Integer> al=new ArrayList();         
          
            for (int j = 0; j < al45.size(); j++) {
               remove(al45.get(j));
                
            }
     while(rs.next())
    {
    al.add(rs.getInt("seat_no"));
    }
          
      int i=1;
    int x=40;
    int y=150;

   while(i<=seat){
           JButton c=new JButton(""+i);
           al45.add(c);
     c.setBounds(x,y, 55, 40);
     c.setFont(new java.awt.Font("Segoe UI", 0, 10));
     c.addActionListener(new mylistener(c,i));
     add(c);
     x=x+60;
     if(875<=x){
         x=40;
         y=y+50;
        Dimension dim= this.getSize();
        int gy= dim.height;
         System.out.println(gy);
         if(y>gy){
             setSize(dim.width,y+80);
         }
     }
     if(al.contains(i)){
         c.setEnabled(false);
         c.setBackground(Color.gray);
         c.setForeground(Color.black);
     }
     else{
         c.setEnabled(true);
         
         c.setBackground(Color.green);
         c.setForeground(Color.black);
     }
     i++;
   }
            System.out.println(al45.size());
   al.clear();
}
catch(Exception e){
    e.printStackTrace();
}
    }
    
 
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lmov;
    private javax.swing.JLabel lscr;
    private javax.swing.JLabel tscr;
    private javax.swing.JLabel tshowid;
    private javax.swing.JLabel tstart;
    // End of variables declaration//GEN-END:variables

}
