
import java.awt.Color;
import java.awt.Label;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.JLabel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SHIVAM
 */
public class tic_print extends javax.swing.JFrame {
ArrayList<seat> li;
    /** Creates new form tic_print */
    public tic_print(ArrayList<seat> al,String mov,String star,int scr,int day_id) {
        initComponents();
        li=new ArrayList(al);
        String timeStamp=new SimpleDateFormat("dd/MM/yyyy").format(Calendar.getInstance().getTime());
        for (int i = 0; i <li.size(); i++) {
            Label l=new Label(mov);
           l.setBounds(35, i*100+2, 75, 10);
           l.setBackground(Color.white);
           l.setFont(new java.awt.Font("Tahoma", 3, 11));
            Label l1=new Label(star);
           l1.setBounds(158, i*100+18, 40, 10);
           l1.setBackground(Color.white);
           l1.setFont(new java.awt.Font("Tahoma", 3, 11));
           
           Label l2=new Label(timeStamp);
           l2.setBackground(Color.white);
           l2.setBounds(10, i*100+30, 70, 10);
           l2.setFont(new java.awt.Font("Tahoma", 3, 11));
           
           Label l3=new Label(""+scr);
           l3.setBounds(168, i*100+30, 20, 10);
           l3.setBackground(Color.white);
           l3.setFont(new java.awt.Font("Tahoma", 3, 11));
           
           Label l4=new Label(""+li.get(i).seat);
           l4.setBounds(175, i*100+2, 20, 10);
           l4.setBackground(Color.white);
           l4.setFont(new java.awt.Font("Tahoma", 3, 11));
           //int ij=timeStamp.indexOf("/");
           //String s33=timeStamp.substring(0,i);
           //String s34=timeStamp.substring(i);
           //ij=Integer.parseInt(s33);
           //ij=ij+day_id;
           //Label l6=new Label(""+ij+s34);
          Label l6=new Label("23");
           
           l6.setBounds(158, i*100+25, 10, 10);
           l6.setBackground(Color.white);
           l6.setFont(new java.awt.Font("Tahoma", 3, 11));
           
           JLabel l5=new javax.swing.JLabel();
           l5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ticket.jpg")));
            
            
        l5.setBounds(0, i*100, 200, 100);
            add(l);
            add(l1);
            add(l2);
            add(l3);
          add(l4);
            add(l5);
            add(l6);
            
        }
this.setSize(300,3000);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        getContentPane().setLayout(null);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        System.out.println(evt.getX()+" "+evt.getY());        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Window".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tic_print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tic_print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tic_print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tic_print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new tic_print().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
